#!/usr/bin/env node
/**
 * build-icons.js
 * Generates an SVG sprite from Bootstrap Icons for only the icons actually
 * used in the project templates.  Output goes to:
 *   backend/static/images/icons-sprite.svg
 *
 * Usage:  node build-icons.js
 */

const fs   = require('fs');
const path = require('path');

// ── All unique Bootstrap Icon names used across the templates ──────────────
const USED_ICONS = [
  'apple',
  'arrow-clockwise',
  'arrow-left',
  'arrow-repeat',
  'arrow-right',
  'arrows-angle-expand',
  'arrows-fullscreen',
  'arrow-up',
  'arrow-up-circle',
  'aspect-ratio',
  'bar-chart',
  'book',
  'book-half',
  'bookmark-heart',
  'bookmark-plus',
  'bookmark-star',
  'box-arrow-in-right',
  'box-arrow-up-right',
  'bullseye',
  'calendar3',
  'camera',
  'camera-video',
  'camera-video-fill',
  'card-text',
  'check2',
  'check2-circle',
  'check-circle',
  'check-circle-fill',
  'check-lg',
  'chevron-double-left',
  'chevron-double-right',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'clock',
  'clock-fill',
  'clock-history',
  'cloud-arrow-up',
  'cloud-check',
  'cloud-slash',
  'cloud-upload',
  'code-square',
  'collection',
  'collection-play',
  'cpu',
  'dot',
  'download',
  'envelope',
  'exclamation',
  'exclamation-circle',
  'exclamation-circle-fill',
  'exclamation-octagon-fill',
  'exclamation-triangle',
  'exclamation-triangle-fill',
  'eye',
  'eye-slash',
  'facebook',
  'file-earmark-check',
  'file-earmark-pdf',
  'file-earmark-text',
  'file-earmark-word',
  'file-earmark-word-fill',
  'file-earmark-x',
  'file-pdf',
  'files',
  'file-text',
  'filter',
  'funnel',
  'gear',
  'gear-fill',
  'geo-alt',
  'globe',
  'globe2',
  'google-play',
  'graph-up',
  'graph-up-arrow',
  'hdd',
  'hdd-network',
  'headphones',
  'hourglass-split',
  'house',
  'house-door',
  'image',
  'inbox',
  'info-circle',
  'info-circle-fill',
  'instagram',
  'journal-bookmark',
  'journal-bookmark-fill',
  'journal-code',
  'journal-text',
  'key',
  'lightbulb',
  'lightning',
  'link-45deg',
  'list',
  'list-check',
  'list-task',
  'list-ul',
  'lock',
  'magic',
  'mic',
  'music-note',
  'music-note-beamed',
  'pause-circle',
  'pencil',
  'pencil-square',
  'percent',
  'person',
  'person-check',
  'person-fill',
  'person-gear',
  'person-plus',
  'phone',
  'pie-chart',
  'play',
  'play-circle',
  'play-circle-fill',
  'play-fill',
  'plus-lg',
  'printer',
  'question-circle',
  'robot',
  'save',
  'search',
  'send',
  'shield-check',
  'shield-exclamation',
  'shield-lock',
  'sliders',
  'speedometer2',
  'star',
  'star-fill',
  'tag',
  'tags',
  'three-dots-vertical',
  'translate',
  'trash',
  'upload',
  'x-circle',
  'x-circle-fill',
  'x-lg',
  'youtube',
  'zoom-in',
  'zoom-out',
];

// ── Paths ──────────────────────────────────────────────────────────────────
const iconsDir      = path.join(__dirname, 'node_modules', 'bootstrap-icons', 'icons');
const outputDir     = path.join(__dirname, 'backend', 'static', 'images');
const outputFile    = path.join(outputDir, 'icons-sprite.svg');
const templateDir   = path.join(__dirname, 'backend', 'templates', 'includes');
const templateFile  = path.join(templateDir, 'icons-sprite.html');

// ── Ensure output directories exist ──────────────────────────────────────
if (!fs.existsSync(outputDir))   fs.mkdirSync(outputDir,   { recursive: true });
if (!fs.existsSync(templateDir)) fs.mkdirSync(templateDir, { recursive: true });

// ── Build sprite ──────────────────────────────────────────────────────────
let symbols = '';
let missing  = [];

for (const name of USED_ICONS) {
  const svgPath = path.join(iconsDir, `${name}.svg`);
  if (!fs.existsSync(svgPath)) {
    missing.push(name);
    continue;
  }
  let raw = fs.readFileSync(svgPath, 'utf8');

  // Extract everything inside the outer <svg> tag (its inner content)
  const innerMatch = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
  if (!innerMatch) {
    missing.push(name);
    continue;
  }
  const inner = innerMatch[1].trim();

  // Extract viewBox from the original SVG (Bootstrap Icons use 16x16)
  const vbMatch = raw.match(/viewBox="([^"]+)"/);
  const viewBox = vbMatch ? vbMatch[1] : '0 0 16 16';

  symbols += `  <symbol id="bi-${name}" viewBox="${viewBox}">\n    ${inner}\n  </symbol>\n`;
}

const sprite = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Bootstrap Icons SVG Sprite — auto-generated by build-icons.js -->
<!-- Contains only the ${USED_ICONS.length} icons actually used in this project -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     style="display:none;">
${symbols}
</svg>
`;

fs.writeFileSync(outputFile, sprite, 'utf8');

// ── Also write the Django template include (for inline body injection) ────
// The inline version omits the XML declaration and has display:none to hide
// the sprite container from layout.
const templateSprite = `{# Auto-generated by build-icons.js — DO NOT EDIT MANUALLY #}
{# Inline SVG sprite — included once at the top of <body> in base & admin_base #}
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     style="display:none;" aria-hidden="true">
${symbols}
</svg>
`;
fs.writeFileSync(templateFile, templateSprite, 'utf8');

console.log(`✅  SVG sprite written to: ${path.relative(__dirname, outputFile)}`);
console.log(`✅  Django template written to: ${path.relative(__dirname, templateFile)}`);
console.log(`   Symbols: ${USED_ICONS.length - missing.length} icons included`);
if (missing.length) {
  console.warn(`⚠️  Missing icons (check spelling): ${missing.join(', ')}`);
}
