# Generated by Django 5.2.9 on 2025-12-10 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Arabic Name')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='English Name')),
                ('description_ar', models.TextField(blank=True, verbose_name='Arabic Description')),
                ('color', models.CharField(default='#8C1C13', help_text='Hex color code (e.g., #8C1C13)', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name_ar'],
                'indexes': [models.Index(fields=['is_active', 'name_ar'], name='media_manag_is_acti_96ef25_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(db_index=True, max_length=200, verbose_name='Arabic Title')),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='English Title')),
                ('description_ar', models.TextField(verbose_name='Arabic Description')),
                ('description_en', models.TextField(blank=True, verbose_name='English Description')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF')], db_index=True, max_length=10, verbose_name='Content Type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tags', models.ManyToManyField(blank=True, to='media_manager.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, upload_to='original/videos/', verbose_name='Original File')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Duration (seconds)')),
                ('hls_720p_path', models.CharField(blank=True, max_length=500, verbose_name='HLS 720p Path')),
                ('hls_480p_path', models.CharField(blank=True, max_length=500, verbose_name='HLS 480p Path')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Processing Status')),
                ('file_size_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (MB)')),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_manager.contentitem', verbose_name='Content Item')),
            ],
            options={
                'verbose_name': 'Video Metadata',
                'verbose_name_plural': 'Video Metadata',
            },
        ),
        migrations.CreateModel(
            name='AudioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, upload_to='original/audio/', verbose_name='Original File')),
                ('compressed_file', models.FileField(blank=True, upload_to='compressed/audio/', verbose_name='Compressed File')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Duration (seconds)')),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitrate (kbps)')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Processing Status')),
                ('file_size_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (MB)')),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_manager.contentitem', verbose_name='Content Item')),
            ],
            options={
                'verbose_name': 'Audio Metadata',
                'verbose_name_plural': 'Audio Metadata',
                'indexes': [models.Index(fields=['processing_status'], name='media_manag_process_4da723_idx'), models.Index(fields=['duration_seconds'], name='media_manag_duratio_8efab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PdfMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, upload_to='original/pdf/', verbose_name='Original File')),
                ('optimized_file', models.FileField(blank=True, upload_to='optimized/pdf/', verbose_name='Optimized File')),
                ('file_size_mb', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='File Size (MB)')),
                ('page_count', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Page Count')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Processing Status')),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_manager.contentitem', verbose_name='Content Item')),
            ],
            options={
                'verbose_name': 'PDF Metadata',
                'verbose_name_plural': 'PDF Metadata',
                'indexes': [models.Index(fields=['processing_status'], name='media_manag_process_a642b4_idx'), models.Index(fields=['file_size_mb'], name='media_manag_file_si_edee0e_idx'), models.Index(fields=['page_count'], name='media_manag_page_co_3cd00c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type', 'is_active', '-created_at'], name='media_manag_content_39a38e_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['is_active', '-created_at'], name='media_manag_is_acti_f2dc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='videometa',
            index=models.Index(fields=['processing_status'], name='media_manag_process_17cdde_idx'),
        ),
        migrations.AddIndex(
            model_name='videometa',
            index=models.Index(fields=['duration_seconds'], name='media_manag_duratio_8900bc_idx'),
        ),
    ]
