# Generated by Django 5.2.9 on 2025-12-15 08:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='book_content',
            field=models.TextField(blank=True, null=True, verbose_name='Extracted Book Content'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Search Vector'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='media_manag_search__56fb1b_gin'),
        ),
    ]
