# Generated by Django 5.2.9 on 2025-01-29 - Phase 3: Index Strategy Optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_contentitem_book_content_contentitem_search_vector_and_more'),
    ]

    operations = [
        # Phase 3: Strategic index additions based on query analysis
        
        # 1. Optimize tag-based content filtering (from PDF detail "related content" queries)
        # This covers: ContentItem.objects.filter(tags__id__in=tag_ids, content_type='pdf', is_active=True)
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(
                fields=['is_active', 'content_type', '-created_at'], 
                name='media_mgr_active_type_created_idx',
                condition=models.Q(is_active=True),  # Partial index for active content only
            ),
        ),
        
        # 2. Optimize tag content counting queries (popular tags aggregation)
        # This helps: Tag.objects.annotate(content_count=Count('contentitem', filter=Q(contentitem__is_active=True)))
        # The M2M table already has indexes on both FKs, but we can add a covering index
        migrations.RunSQL(
            # Add covering index on M2M table for tag counting performance
            "CREATE INDEX IF NOT EXISTS media_mgr_contentitem_tags_covering_idx ON media_manager_contentitem_tags (tag_id, contentitem_id);",
            reverse_sql="DROP INDEX IF EXISTS media_mgr_contentitem_tags_covering_idx;",
        ),
        
        # 3. Optimize content search with active status (for search functionality)  
        # This covers search queries that filter by is_active and use search_vector
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(
                fields=['is_active'],
                name='media_mgr_active_search_idx',
                condition=models.Q(is_active=True) & ~models.Q(search_vector__isnull=True),
            ),
        ),
        
        # 4. Optimize title-based lookups for different languages
        # Covers admin search and content management filtering
        migrations.AddIndex(
            model_name='contentitem', 
            index=models.Index(
                fields=['content_type', 'title_ar'],
                name='media_mgr_type_title_ar_idx',
            ),
        ),
        
        # 5. Add index on Tag.is_active for tag filtering queries
        # This covers Tag.objects.filter(is_active=True) used in popular tags
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(
                fields=['is_active', '-created_at'],
                name='media_mgr_tag_active_created_idx',
            ),
        ),
    ]
