# Generated by Django 5.2.9 on 2025-01-29 - Phase 3: Final Index Strategy Optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0003_phase3_index_optimizations'),
    ]

    operations = [
        # Phase 3: Final strategic index additions
        
        # 1. Add updated_at index for cache invalidation and change tracking
        # Useful for: ContentItem.objects.filter(updated_at__gte=last_update)
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(
                fields=['-updated_at'],
                name='media_mgr_updated_at_idx',
            ),
        ),
        
        # 2. Optimize UUID lookups with content type (for detail views)
        # This covers get_object_or_404(ContentItem, id=uuid, content_type='pdf')
        # Note: Primary key lookups are already fast, but this helps with combined filters
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(
                fields=['content_type'],  # Most selective first
                name='media_mgr_type_lookup_idx', 
                condition=models.Q(is_active=True),  # Partial index
            ),
        ),

        # 3. Add compound index for tag name lookups with language preference
        # Covers Tag.objects.filter(is_active=True).order_by('name_ar')
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(
                fields=['is_active', 'name_ar'],
                name='media_mgr_tag_active_name_idx',
            ),
        ),
    ]
