# Generated by Django 5.2.9 on 2026-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_phase3_final_optimizations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentitem',
            name='media_mgr_active_search_idx',
        ),
        migrations.RenameIndex(
            model_name='contentitem',
            new_name='mgr_active_type_created_idx',
            old_name='media_mgr_active_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contentitem',
            new_name='mgr_type_title_ar_idx',
            old_name='media_mgr_type_title_ar_idx',
        ),
        migrations.RenameIndex(
            model_name='contentitem',
            new_name='mgr_type_lookup_idx',
            old_name='media_mgr_type_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='contentitem',
            new_name='mgr_updated_at_idx',
            old_name='media_mgr_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='mgr_tag_active_created_idx',
            old_name='media_mgr_tag_active_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='mgr_tag_active_name_idx',
            old_name='media_mgr_tag_active_name_idx',
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(condition=models.Q(('is_active', True), ('search_vector__isnull', False)), fields=['is_active'], name='mgr_active_search_idx'),
        ),
    ]
