# Generated migration for SEO metadata integration - Modified for SQLite compatibility
# Run: python manage.py makemigrations media_manager --name add_seo_fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0005_phase3_model_indexes'),  # Updated to come after phase3 migrations
    ]

    operations = [
        # Add SEO metadata fields to ContentItem - Using TextField for SQLite compatibility
        migrations.AddField(
            model_name='contentitem',
            name='tags_en',
            field=models.TextField(
                blank=True,
                default='',
                help_text='English tags for SEO (comma-separated, max 6 tags)',
                verbose_name='English Tags'
            ),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_keywords_ar',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Arabic SEO keywords generated by AI (comma-separated, max 30)',
                verbose_name='Arabic SEO Keywords'
            ),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_keywords_en',
            field=models.TextField(
                blank=True,
                default='',
                help_text='English SEO keywords generated by AI (comma-separated, max 30)',
                verbose_name='English SEO Keywords'
            ),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_meta_description_ar',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Arabic meta description for search engines (max 160 chars)',
                max_length=160,
                verbose_name='Arabic Meta Description'
            ),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_meta_description_en',
            field=models.CharField(
                blank=True,
                default='',
                help_text='English meta description for search engines (max 160 chars)',
                max_length=160,
                verbose_name='English Meta Description'
            ),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_title_suggestions',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Alternative SEO titles for search optimization (comma-separated, max 3)',
                verbose_name='SEO Title Suggestions'
            ),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='structured_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON-LD structured data for search engines',
                null=True,
                verbose_name='Structured Data'
            ),
        ),
        
        # Add indexes for SEO fields performance - SQLite compatible
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(
                fields=['is_active', 'content_type'],
                name='seo_active_type_idx'
            ),
        ),
        # Note: Removed duplicate updated_at index as it's already created in phase3 migrations
    ]