# Generated by Django 5.2.9 on 2026-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0006_add_seo_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentitem',
            name='seo_active_type_idx',
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='seo_meta_description_ar',
            field=models.CharField(blank=True, help_text='Arabic meta description for search engines (max 160 chars)', max_length=160, verbose_name='Arabic Meta Description'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='seo_meta_description_en',
            field=models.CharField(blank=True, help_text='English meta description for search engines (max 160 chars)', max_length=160, verbose_name='English Meta Description'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data for search engines', verbose_name='Structured Data'),
        ),
    ]
