# Generated by Django 5.2.9 on 2026-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0007_remove_contentitem_seo_active_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiometa',
            name='r2_compressed_file_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the compressed audio file (if uploaded)', max_length=1000, verbose_name='R2 Compressed File URL'),
        ),
        migrations.AddField(
            model_name='audiometa',
            name='r2_original_file_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the original audio file (if uploaded)', max_length=1000, verbose_name='R2 Original File URL'),
        ),
        migrations.AddField(
            model_name='audiometa',
            name='r2_upload_progress',
            field=models.PositiveIntegerField(blank=True, help_text='Upload progress percentage (0-100)', null=True, verbose_name='R2 Upload Progress (%)'),
        ),
        migrations.AddField(
            model_name='audiometa',
            name='r2_upload_status',
            field=models.CharField(blank=True, default='', help_text='Status of R2 upload: pending, uploading, completed, failed', max_length=32, verbose_name='R2 Upload Status'),
        ),
        migrations.AddField(
            model_name='pdfmeta',
            name='r2_optimized_file_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the optimized PDF file (if uploaded)', max_length=1000, verbose_name='R2 Optimized File URL'),
        ),
        migrations.AddField(
            model_name='pdfmeta',
            name='r2_original_file_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the original PDF file (if uploaded)', max_length=1000, verbose_name='R2 Original File URL'),
        ),
        migrations.AddField(
            model_name='pdfmeta',
            name='r2_upload_progress',
            field=models.PositiveIntegerField(blank=True, help_text='Upload progress percentage (0-100)', null=True, verbose_name='R2 Upload Progress (%)'),
        ),
        migrations.AddField(
            model_name='pdfmeta',
            name='r2_upload_status',
            field=models.CharField(blank=True, default='', help_text='Status of R2 upload: pending, uploading, completed, failed', max_length=32, verbose_name='R2 Upload Status'),
        ),
        migrations.AddField(
            model_name='videometa',
            name='r2_hls_480p_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for 480p HLS playlist (if uploaded)', max_length=1000, verbose_name='R2 HLS 480p URL'),
        ),
        migrations.AddField(
            model_name='videometa',
            name='r2_hls_720p_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for 720p HLS playlist (if uploaded)', max_length=1000, verbose_name='R2 HLS 720p URL'),
        ),
        migrations.AddField(
            model_name='videometa',
            name='r2_original_file_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the original video file (if uploaded)', max_length=1000, verbose_name='R2 Original File URL'),
        ),
        migrations.AddField(
            model_name='videometa',
            name='r2_upload_progress',
            field=models.PositiveIntegerField(blank=True, help_text='Upload progress percentage (0-100)', null=True, verbose_name='R2 Upload Progress (%)'),
        ),
        migrations.AddField(
            model_name='videometa',
            name='r2_upload_status',
            field=models.CharField(blank=True, default='', help_text='Status of R2 upload: pending, uploading, completed, failed', max_length=32, verbose_name='R2 Upload Status'),
        ),
    ]
