# Generated by Django 5.2.9 on 2026-02-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_arabic_search_optimization'),
        ('media_manager', '0008_add_r2_fields'),
    ]

    operations = [
    ]
