# Generated by Django 5.2.9 on 2026-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0009_merge_20260203_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='SEO Processing Status'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Active'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(condition=models.Q(('content_type', 'pdf')), fields=['content_type', 'processing_status'], name='mgr_pdf_processing_idx'),
        ),
    ]
