# Generated by Django 5.2.9 on 2026-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0010_contentitem_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional study notes or context', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_title_ar',
            field=models.CharField(blank=True, help_text='Optimized Arabic title for search engines (max 70 chars)', max_length=70, verbose_name='Arabic SEO Title'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Optimized English title for search engines (max 70 chars)', max_length=70, verbose_name='English SEO Title'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full text transcript of audio/video or summary for SEO', null=True, verbose_name='Transcript'),
        ),
    ]
