# Generated by Django 5.2.9 on 2026-02-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0013_add_unique_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycontentviewsummary',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of views', verbose_name='View Count'),
        ),
    ]
