# Generated by Django 5.2.9 on 2026-02-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0014_alter_dailycontentviewsummary_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(default='Christian Library', max_length=255)),
                ('site_name_ar', models.CharField(default='المكتبة المسيحية', max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to the organization logo')),
                ('website_url', models.URLField(blank=True, help_text='Primary website URL')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text="Bilingual JSON-LD for Organization. Use {'en': {...}, 'ar': {...}} structure.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
