# Generated by Django - Merge migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0015_siteconfiguration'),
        ('media_manager', '0015_update_search_vector_multilingual'),
    ]

    operations = [
        # This is a merge migration, no operations needed
    ]
