# Generated by Django - Add search sensitivity settings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0016_merge_20260214_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='search_sensitivity_mode',
            field=models.CharField(
                choices=[
                    ('exact', 'Exact Match - Words must appear exactly'),
                    ('strict', 'Strict - Only highly relevant matches'),
                    ('normal', 'Normal - Balanced results (Recommended)'),
                    ('relaxed', 'Relaxed - More inclusive results'),
                    ('custom', 'Custom - Manual threshold'),
                ],
                default='normal',
                help_text='Controls how strict the full-text search matching is across the site',
                max_length=20,
                verbose_name='Search Sensitivity Mode',
            ),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='search_custom_threshold',
            field=models.FloatField(
                default=0.1,
                help_text='Custom search threshold value (0.0-1.0). Lower values return more results. Only used when mode is "Custom".',
                verbose_name='Custom Search Threshold',
            ),
        ),
    ]
