# Generated by Django 5.2.11 on 2026-02-19 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0017_add_search_sensitivity_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='title_ar',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Arabic Title'),
        ),
        migrations.CreateModel(
            name='APIUploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_hash', models.CharField(help_text='SHA256 hash of API key for tracking', max_length=64, verbose_name='API Key Hash')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='Status Code')),
                ('files_count', models.IntegerField(default=0, verbose_name='Files Count')),
                ('request_size_mb', models.FloatField(default=0.0, verbose_name='Request Size (MB)')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Response Time (ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'API Upload Log',
                'verbose_name_plural': 'API Upload Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key_hash', 'created_at'], name='media_manag_api_key_688b12_idx'), models.Index(fields=['status_code', 'created_at'], name='media_manag_status__546bc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUploadQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_path', models.CharField(max_length=500, verbose_name='Temporary File Path')),
                ('doc_file_path', models.CharField(blank=True, help_text='Path to Word document for book content extraction', max_length=500, null=True, verbose_name='Document File Path')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF')], db_index=True, max_length=10, verbose_name='Content Type')),
                ('file_size_mb', models.FloatField(verbose_name='File Size (MB)')),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata for content item', null=True, verbose_name='Metadata')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('queue_status', models.CharField(choices=[('waiting', 'Waiting'), ('delayed', 'Delayed'), ('ready', 'Ready')], db_index=True, default='waiting', max_length=20, verbose_name='Queue Status')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When to process this item (for rate limit handling)', null=True, verbose_name='Scheduled For')),
                ('delay_count', models.IntegerField(default=0, help_text='Number of times processing was delayed (max 7)', verbose_name='Delay Count')),
                ('priority', models.IntegerField(default=0, help_text='Higher values = higher priority', verbose_name='Priority')),
                ('gemini_attempts', models.IntegerField(default=0, help_text='Number of attempts to generate metadata with Gemini', verbose_name='Gemini Attempts')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('content_item', models.ForeignKey(blank=True, help_text='Created content item after processing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.contentitem', verbose_name='Content Item')),
            ],
            options={
                'verbose_name': 'API Upload Queue Item',
                'verbose_name_plural': 'API Upload Queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'queue_status', 'scheduled_for'], name='media_manag_status_5a6a69_idx'), models.Index(fields=['content_type', 'status'], name='media_manag_content_551947_idx'), models.Index(fields=['created_at'], name='media_manag_created_20cebe_idx')],
            },
        ),
    ]
