# Generated by Django 5.2.9 on 2026-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0019_add_supplementary_document_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuploadqueue',
            name='thumbnail_path',
            field=models.CharField(blank=True, help_text='Path to uploaded thumbnail image', max_length=500, null=True, verbose_name='Thumbnail Path'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='r2_thumbnail_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 URL for the thumbnail image', max_length=1000, verbose_name='R2 Thumbnail URL'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Item thumbnail (auto-generated if empty for PDFs/Videos)', null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Thumbnail'),
        ),
    ]
