# Generated by Django 5.2.12 on 2026-05-16 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_manager", "0020_apiuploadqueue_thumbnail_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("file_processing", "File Processing"),
                            ("text_extraction", "Text Extraction"),
                            ("r2_upload", "R2 Upload"),
                            ("seo_generation", "SEO Generation"),
                            ("completed", "Completed"),
                        ],
                        default="file_processing",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_stage", models.CharField(blank=True, max_length=30)),
                ("failure_reason", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_job",
                        to="media_manager.contentitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "current_stage"],
                        name="media_manag_status_8b8d93_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="media_manag_status_441653_idx",
                    ),
                ],
            },
        ),
    ]
