# Generated by Django 5.2.12 on 2026-05-22 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_manager", "0021_add_processing_job_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkedUploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_size", models.BigIntegerField()),
                ("current_offset", models.BigIntegerField(default=0)),
                ("is_complete", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("staging_path", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_complete", "updated_at"],
                        name="media_manag_is_comp_894bf0_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="media_manag_created_e432e2_idx"
                    ),
                ],
            },
        ),
    ]
