# Generated by Django 5.1.4 on 2026-06-05 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_manager", "0025_contentlifecycleauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiGenerationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_model_key", models.CharField(db_index=True, max_length=64)),
                (
                    "resolved_model_key",
                    models.CharField(db_index=True, max_length=64, null=True),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("combined", "Combined (Metadata + SEO)"),
                            ("metadata", "Metadata Only"),
                            ("seo", "SEO Only"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("timeout", "Timeout"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("success", models.BooleanField(null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("response_time_ms", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Gemini Generation Attempt",
                "verbose_name_plural": "Gemini Generation Attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeminiModelSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("display_name", models.CharField(max_length=128)),
                ("provider", models.CharField(default="google", max_length=32)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("fallback_priority", models.IntegerField(default=0)),
                ("limit_per_minute", models.IntegerField(default=5)),
                ("limit_per_day", models.IntegerField(default=20)),
                ("limit_per_month", models.IntegerField(blank=True, null=True)),
                ("request_timeout_seconds", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gemini Model Setting",
                "verbose_name_plural": "Gemini Model Settings",
                "ordering": ["fallback_priority", "model_key"],
            },
        ),
        migrations.RenameIndex(
            model_name="contentlifecycleauditlog",
            new_name="media_manag_content_7f0ae7_idx",
            old_name="media_manage_content_4f58cc_idx",
        ),
        migrations.RenameIndex(
            model_name="contentlifecycleauditlog",
            new_name="media_manag_action__70b46c_idx",
            old_name="media_manage_action__fd7b6b_idx",
        ),
        migrations.RenameIndex(
            model_name="contentlifecycleauditlog",
            new_name="media_manag_actor_i_9706a0_idx",
            old_name="media_manage_actor_i_b8d001_idx",
        ),
        migrations.RenameIndex(
            model_name="contentlifecycleauditlog",
            new_name="media_manag_new_sta_e486e6_idx",
            old_name="media_manage_new_sta_2e5eb2_idx",
        ),
        migrations.RemoveField(
            model_name="apiuploadqueue",
            name="gemini_attempts",
        ),
        migrations.AddField(
            model_name="geminigenerationattempt",
            name="content_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="media_manager.contentitem",
            ),
        ),
        migrations.AddIndex(
            model_name="geminigenerationattempt",
            index=models.Index(
                fields=["content_item", "created_at"],
                name="media_manag_content_b8f664_idx",
            ),
        ),
    ]
