# Generated by Django 5.2.12 on 2026-06-06 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_manager", "0027_seed_gemini_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="geminimodelsetting",
            name="max_input_tokens",
            field=models.IntegerField(
                default=128000,
                help_text="Model context window limit (e.g. 128000 for Gemini 1.5 Pro)",
            ),
        ),
        migrations.AddField(
            model_name="geminimodelsetting",
            name="tokens_per_day",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum input tokens allowed per day (NULL = no per-day limit)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="geminimodelsetting",
            name="tokens_per_minute",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum input tokens allowed per minute (NULL = no per-minute limit)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GeminiModelConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_key", models.CharField(db_index=True, max_length=64)),
                ("date", models.DateField(db_index=True)),
                ("minute_slot", models.PositiveSmallIntegerField()),
                ("tokens_consumed", models.IntegerField(default=0)),
                ("requests_consumed", models.IntegerField(default=0)),
                ("is_finalized", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gemini Model Consumption",
                "verbose_name_plural": "Gemini Model Consumption Records",
                "indexes": [
                    models.Index(
                        fields=["model_key", "date", "is_finalized"],
                        name="media_manag_model_k_e7b045_idx",
                    ),
                    models.Index(
                        fields=["date", "minute_slot"],
                        name="media_manag_date_bf73b2_idx",
                    ),
                ],
                "unique_together": {("model_key", "date", "minute_slot")},
            },
        ),
    ]
