# Generated by Django 5.1.4 on 2026-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_manager", "0028_geminimodelsetting_max_input_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geminimodelsetting",
            name="max_concurrency",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of concurrent API requests allowed for this model",
            ),
        ),
    ]
