# Generated by Django for Google Indexing Queue models
# Migration for GoogleIndexingQueue and GoogleIndexingQuota models

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_api', '0001_initial'),
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIndexingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Full URL to submit to Google', max_length=500, verbose_name='URL')),
                ('action', models.CharField(choices=[('URL_UPDATED', 'URL Updated'), ('URL_DELETED', 'URL Deleted')], default='URL_UPDATED', max_length=20, verbose_name='Action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('quota_exceeded', 'Quota Exceeded'), ('invalid', 'Invalid - Missing SEO/Metadata')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=5, help_text='Higher priority items processed first (1-10)', verbose_name='Priority')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Error Code')),
                ('google_response', models.JSONField(blank=True, help_text='Full response from Google Indexing API', null=True, verbose_name='Google Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When to process this item (for quota management)', null=True, verbose_name='Scheduled For')),
                ('content_item', models.ForeignKey(blank=True, help_text='Reference to content item (null if deleted)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indexing_queue', to='media_manager.contentitem', verbose_name='Content Item')),
            ],
            options={
                'verbose_name': 'Google Indexing Queue Item',
                'verbose_name_plural': 'Google Indexing Queue Items',
                'ordering': ['-priority', 'created_at'],
                'indexes': [
                    models.Index(fields=['status', '-priority', 'created_at'], name='frontend_ap_status_c31f20_idx'),
                    models.Index(fields=['scheduled_for', 'status'], name='frontend_ap_schedul_35b7e6_idx'),
                    models.Index(fields=['-created_at'], name='frontend_ap_created_5e9c3f_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='GoogleIndexingQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('requests_used', models.IntegerField(default=0, verbose_name='Requests Used')),
                ('requests_failed', models.IntegerField(default=0, verbose_name='Requests Failed')),
                ('last_reset_at', models.DateTimeField(auto_now=True, verbose_name='Last Reset At')),
            ],
            options={
                'verbose_name': 'Google Indexing Quota',
                'verbose_name_plural': 'Google Indexing Quotas',
                'ordering': ['-date'],
            },
        ),
    ]
