# Generated by Django 5.2.12 on 2026-03-21 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend_api", "0002_google_indexing_queue"),
        ("media_manager", "0020_apiuploadqueue_thumbnail_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleIndexedUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True, max_length=500, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "url_type",
                    models.CharField(
                        choices=[
                            ("content", "Content Item"),
                            ("static_page", "Static Page"),
                            ("tag_page", "Tag Page"),
                            ("rss_feed", "RSS Feed"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="URL Type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "Arabic"),
                            ("en", "English"),
                            ("both", "Language-Neutral"),
                        ],
                        db_index=True,
                        max_length=5,
                        verbose_name="Language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_indexed", "Not Indexed"),
                            ("pending", "Pending Submission"),
                            ("indexed", "Successfully Indexed"),
                            ("failed", "Indexing Failed"),
                            ("deleted", "URL Deleted"),
                        ],
                        db_index=True,
                        default="not_indexed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "needs_reindex",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marked for re-submission (force re-index)",
                        verbose_name="Needs Re-indexing",
                    ),
                ),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="Submission Count"),
                ),
                (
                    "last_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Submitted At"
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Indexed At"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="Last Error")),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Last Error Code"
                    ),
                ),
                (
                    "last_google_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Last Google Response"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Google Indexed URL",
                "verbose_name_plural": "Google Indexed URLs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="googleindexingqueue",
            new_name="frontend_ap_status_efca2c_idx",
            old_name="frontend_ap_status_c31f20_idx",
        ),
        migrations.RenameIndex(
            model_name="googleindexingqueue",
            new_name="frontend_ap_schedul_7bcb7a_idx",
            old_name="frontend_ap_schedul_35b7e6_idx",
        ),
        migrations.RenameIndex(
            model_name="googleindexingqueue",
            new_name="frontend_ap_created_ffc421_idx",
            old_name="frontend_ap_created_5e9c3f_idx",
        ),
        migrations.RenameIndex(
            model_name="googlereindexingtask",
            new_name="frontend_ap_created_7a2fa5_idx",
            old_name="frontend_ap_created_85e5f0_idx",
        ),
        migrations.RenameIndex(
            model_name="googlereindexingtask",
            new_name="frontend_ap_status_0f4360_idx",
            old_name="frontend_ap_status_dca1b9_idx",
        ),
        migrations.AddField(
            model_name="googleindexedurl",
            name="content_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indexed_urls",
                to="media_manager.contentitem",
                verbose_name="Content Item",
            ),
        ),
        migrations.AddField(
            model_name="googleindexedurl",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indexed_urls",
                to="media_manager.tag",
                verbose_name="Tag",
            ),
        ),
        migrations.AddIndex(
            model_name="googleindexedurl",
            index=models.Index(
                fields=["status", "needs_reindex"], name="frontend_ap_status_3d5594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="googleindexedurl",
            index=models.Index(
                fields=["url_type", "language", "status"],
                name="frontend_ap_url_typ_283c9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="googleindexedurl",
            index=models.Index(
                fields=["content_item", "language"],
                name="frontend_ap_content_3aa326_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="googleindexedurl",
            index=models.Index(
                fields=["-last_submitted_at"], name="frontend_ap_last_su_3ab885_idx"
            ),
        ),
    ]
