# Generated by Django 5.2.12 on 2026-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend_api", "0003_add_indexed_url_registry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleIndexingQuota",
        ),
        migrations.DeleteModel(
            name="GoogleIndexedUrl",
        ),
        migrations.DeleteModel(
            name="GoogleIndexingQueue",
        ),
        migrations.DeleteModel(
            name="GoogleReindexingTask",
        ),
    ]
