# Generated by Django 5.2.12 on 2026-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend_api", "0003_add_indexed_url_registry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googleindexedurl",
            name="content_item",
        ),
        migrations.RemoveField(
            model_name="googleindexedurl",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="googleindexingqueue",
            name="content_item",
        ),
        migrations.DeleteModel(
            name="GoogleIndexingQuota",
        ),
        migrations.RemoveField(
            model_name="googlereindexingtask",
            name="initiated_by",
        ),
        migrations.DeleteModel(
            name="GoogleIndexedUrl",
        ),
        migrations.DeleteModel(
            name="GoogleIndexingQueue",
        ),
        migrations.DeleteModel(
            name="GoogleReindexingTask",
        ),
    ]
