name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pull Latest & Run Docker Compose
        run: |
          cd ${{ secrets.VPS_PROJECT_PATH }}
          git fetch origin
          git reset --hard origin/main
          docker compose build
          docker compose up -d
          docker compose ps
